### ISSUE TITLE
Process should exit cleanly when no release

### ISSUE THREAD

**Issue by dnr-len** [ietf-tools/semver-action#20]
Currently the process exits with error during documentation or other non Major/Minor/Fix release. 
This causes a significant amount of un necessary notifications.

**Comment by NGPixel** [comment]
This is the intended behavior. It wouldn't make sense to create a release if the version number has not changed since the last one. Exiting with error is the right thing to do in this case.

An option could be added to exit silently, but that's definitely not the desired default behavior.

**Comment by NGPixel** [comment]
Added `noVersionBumpBehavior` option in v1.3.0.
