### ISSUE TITLE
Feature Request: add a prefix option

### ISSUE THREAD

**Issue by anden-dev** [ietf-tools/semver-action#27]
Hi, 

I use this action and love it, great work.

I would like to propose adding a prefix option to support semver tags with a prefix.

Example workflow for a tag [reloader](https://github.com/stakater/Reloader)

```sh
    - name: 'Get Previous Tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: NA
          prefix: reloader/
     - name: 'Get Next Tag'
        id: nexttag
        uses: "ietf-tools/semver-action@v1"
        with:
          branch: master
          noVersionBumpBehavior: warn
          prefix: reloader/

```

**Get Previous Tag**
`reloader/v0.1.0`
**Get Next Tag**
`reloader/v0.2.0`

This would allow the use of this action in monorepos.

Currently, the action does not support prefixed tags

```sh
    - name: Get Next Version
        id: semvers
        uses: "ietf-tools/semver-action@v1"
        with:
          branch: master
          noVersionBumpBehavior: warn
```

so for `reloader/v0.1.0` you will receive:

`Error: Latest tag is invalid (does not conform to semver)!`

which is to be expected.

Here is also a related discussion: https://github.com/renovatebot/renovate/issues/14546

**Comment by NGPixel** [comment]
Added in v1.4.0
