### ISSUE TITLE
Support Major version bump using ! char

### ISSUE THREAD

**Issue by drahamim** [ietf-tools/semver-action#30]
I know its an optional part of the Conventional Commit spec but being able to use the `!` character for Major version bumps allows for more flexibility in workflow when merging PRs.

**Comment by NGPixel** [comment]
This is already supported?

Both `type!: message` and `type(scope)!: message` results in a major bump.

**Comment by drahamim** [comment]
ah... I figured out where I went wrong. I had it before scope. thats why it failed. 
ex `feat!(scope): ` or prefixed. I didn't try suffix after scope.... 

Feel free to ignore my derp. Nothing to see here.....
