### ISSUE TITLE
Request: "patch" option for noVersionBumpBehavior

### ISSUE THREAD

**Issue by houserx-jmcc** [ietf-tools/semver-action#33]
This may be an edge case, but there are some situations where we want to force a version increment even when no matching commits found. For example, we have only one commit being tracked and there is a typo in it, so it does not resolve to a version bump. 

We still would release the commit in this case, so an option to default to a patch version bump when "noVersionBumpBehavior" is true would be really handy for edge cases.

**Comment by NGPixel** [comment]
If you only have 1 commit, wouldn't it make more sense to fix the commit message instead?

**Comment by houserx-jmcc** [comment]
> If you only have 1 commit, wouldn't it make more sense to fix the commit message instead?

Well, that is a simple hypothetical example :) 

> You can also set patchAll to true for the same behavior...

Per my reading of the docs, doesn't this then not allow minor or major versions?

**Comment by NGPixel** [comment]
No, it means that anything that is not major or minor will be counted as patch.

**Comment by houserx-jmcc** [comment]
Ah! That is perfect then. I misunderstood it, thanks for clarifying!
