### ISSUE TITLE
Support more prefixes, according to official docs

### ISSUE THREAD

**Issue by geo-sot** [ietf-tools/semver-action#37]
Hello, and many thanks for your efforts

According to official Docs https://www.conventionalcommits.org/en/v1.0.0/, we are able to use these prefixes too
>  build:, chore:, ci:, docs:, style:,

but are not supported yet. Is is ease for you to add them?

**Comment by NGPixel** [comment]
These are already supported...

**Comment by geo-sot** [comment]
'Chore' at least, doesn't seem to be recognized 

You may see the action ran

![image](https://github.com/ietf-tools/semver-action/assets/114676003/4ee30281-91a5-41d0-be42-1f0b277d1c5c)


and the `action.yml` below

![image](https://github.com/ietf-tools/semver-action/assets/114676003/67d4e328-b2b6-45db-aafe-72cc8c4e6003)

**Comment by NGPixel** [comment]
You need to define the `patchList` you want, as explained in https://github.com/ietf-tools/semver-action#inputs

`chore` is excluded by default.

**Comment by geo-sot** [comment]
This was the backup plan. :wink:  Thank you
