### ISSUE TITLE
Feature request: Patch if invalid - noVersionBumpBehavior

### ISSUE THREAD

**Issue by g-otn** [ietf-tools/semver-action#41]
Hello, thank you for this great GitHub action!

I'd like to hear your opinion on a new option:
I want the action to create a patch version if no commit resulted in a version bump since last the release.

For example, 
- If I make a commit that doesn't follow conventional commits (e.g GitHub editor), or
- If a GitHub Action or App occasionally creates a commit into the branch whose message I cannot configure, and it doesn't follow conventional commits.
While at the same time, these changes should be in a new version.

So instead of:
```
Run ietf-tools/semver-action@v1
Comparing against latest tag: 1.0.0
[INVALID] Skipping commit aaa as it doesn't follow conventional commit format.
...
[INVALID] Skipping commit bbb as it doesn't follow conventional commit format.
Error: No commit resulted in a version bump since last release!
```
Do:
```
Run ietf-tools/semver-action@v1
Comparing against latest tag: 1.0.0
[INVALID] Skipping commit aaa as it doesn't follow conventional commit format.
...
[INVALID] Skipping commit bbb as it doesn't follow conventional commit format.
[PATCH]: No commit resulted in a version bump since last release! This will cause a patch version bump.
```
It'd be like a new `patch` option to the `noVersionBumpBehavior` config.

What are your thoughts?

**Comment by NGPixel** [comment]
Added in v1.7.0
