### ISSUE TITLE
Enable ignoring BREAKING CHANGE if v0 and instructed to

### ISSUE THREAD

**Issue by schmidtw** [ietf-tools/semver-action#42]
During the v0 phase of semver it is ok to create breaking changes and not automatically rev the major version.  It would be helpful if there was an optional input field that allowed for treating `BREAKING CHANGE` in the message as a `minor` bump if the current major version value of 0 is present.

**Comment by NGPixel** [comment]
Why are you using BREAKING CHANGE during a v0 phase? There's no prior major version, so what are you breaking from? This doesn't make any sense IMO.

Avoid using BREAKING CHANGE while in v0, as it's not appropriate here...

**Comment by schmidtw** [comment]
In my use case, I have a a team of folks writing a number of v0 libraries at the same time & until we're ready to v1 release them the libraries are depending on one another.  Generally we can do what you describe, but sometimes mistakes happen.  Honestly `v0` rules are pretty brutal, but I'm just trying to make them less painful when we must exist inside them.

Given you implemented #43 (thank you!) I can probably develop a work around for at least catching this case & not releasing & simply requiring manual intervention (releasing a minor release) when it happens outside this plugin.
