### ISSUE TITLE
Provide additional output variable making changes easier to work with.

### ISSUE THREAD

**Issue by schmidtw** [ietf-tools/semver-action#43]
It would be helpful to have an output variable to help explain the change:

`whatChanged` = `nothing`, `patch`, `minor`, `major`

This allows workflows to potentially do different things easier by breaking out this type of detail.  Specifically, I could then conditionally not automatically release if the workflow detected a `major` change pretty easily.

**Comment by NGPixel** [comment]
Added `bump` output variable in v1.8.0
