### ISSUE TITLE
How bump major version?

### ISSUE THREAD

**Issue by patsevanton** [ietf-tools/semver-action#47]
Hello! Thanks for semver-action
I try bump major version:
https://github.com/patsevanton/test-docker-images2/commit/84976dce4a4fd6c0f0b9a50409bdf860fe5a682e
https://github.com/patsevanton/test-docker-images2/commit/42d30a836f9e67d720aebe99ea318bb52777419b

Both issue get error.
How bump major version?

**Comment by NGPixel** [comment]
You're using an invalid prefix and not putting the BREAKING CHANGE term in the correct location.

Read the [conventional commits documentation](https://www.conventionalcommits.org/en/v1.0.0/#summary).
